# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uix.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 628)
        MainWindow.setStyleSheet("background-image: linear-gradient(180deg, red, yellow);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 611, 701))
        self.frame.setStyleSheet("color: qlineargradient(spread:pad, x1:0.607, y1:0.522727, x2:1, y2:0, stop:0 rgba(193, 189, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: #3F5EFB;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.vikno = QtWidgets.QLineEdit(self.frame)
        self.vikno.setGeometry(QtCore.QRect(30, 20, 531, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.vikno.setFont(font)
        self.vikno.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vikno.setStyleSheet("background-color: rgba(255,203,184,0);\n"
"color: white;\n"
"border-radius: 30px;\n"
"border-style: solid;\n"
"border-width: 4px 4px 4px 4px;\n"
"border-color: white;")
        self.vikno.setText("")
        self.vikno.setAlignment(QtCore.Qt.AlignCenter)
        self.vikno.setObjectName("vikno")
        self.Button = QtWidgets.QPushButton(self.frame)
        self.Button.setGeometry(QtCore.QRect(40, 130, 511, 85))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Button.setFont(font)
        self.Button.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    border-style: solid;\n"
"    color: white;\n"
"    background-color:#3F5EFB;\n"
"    border-color: white;\n"
"    border-width: 4px 4px 4px 4px;\n"
"}\n"
"QPushButton::pressed{\n"
"    background: rgba(0, 0, 0, 0)\n"
"}")
        self.Button.setObjectName("Button")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(30, 200, 541, 141))
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.invisible_edit = QtWidgets.QLineEdit(self.frame)
        self.invisible_edit.setGeometry(QtCore.QRect(32, 300, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(False)
        self.invisible_edit.setFont(font)
        self.invisible_edit.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 30px;\n"
"color: white;")
        self.invisible_edit.setText("")
        self.invisible_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.invisible_edit.setObjectName("invisible_edit")
        self.inviseble_edit2 = QtWidgets.QLineEdit(self.frame)
        self.inviseble_edit2.setGeometry(QtCore.QRect(30, 340, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inviseble_edit2.setFont(font)
        self.inviseble_edit2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 30px;\n"
"color: white;")
        self.inviseble_edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.inviseble_edit2.setObjectName("inviseble_edit2")
        self.inviseble_edit3 = QtWidgets.QLineEdit(self.frame)
        self.inviseble_edit3.setGeometry(QtCore.QRect(30, 380, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inviseble_edit3.setFont(font)
        self.inviseble_edit3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 30px;\n"
"color: white;")
        self.inviseble_edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.inviseble_edit3.setObjectName("inviseble_edit3")
        self.inviseble_edit4 = QtWidgets.QLineEdit(self.frame)
        self.inviseble_edit4.setGeometry(QtCore.QRect(30, 440, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inviseble_edit4.setFont(font)
        self.inviseble_edit4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 30px;\n"
"color: white;")
        self.inviseble_edit4.setAlignment(QtCore.Qt.AlignCenter)
        self.inviseble_edit4.setObjectName("inviseble_edit4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button.setText(_translate("MainWindow", "ДІЗНАТИСЬ ПОГОДУ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
